import React from "react";
import { navigate } from "@reach/router";
import { Formik, Field, Form } from "formik";

function AddCategory() {
	const handleSubmit = values => {
		const requestCategories = async () => {
		// We get the CSRF token generated by Rails to send it
		// as a header in the request to create a new post.
		// This is needed because with this token, Rails is going to
		// recognize the request as a valid request
		const csrfToken = document.querySelector("meta[name=csrf-token]").content;
		const response = await fetch("/api/categories", {
			method: "POST",
			credentials: "include",
			headers: {
				"Content-Type": "application/vnd.api+json",
				"X-CSRF-Token": csrfToken
			},
			body: JSON.stringify({ data: values })
		});
		if (response.status === 201) {
			navigate("/");
		}
	};
	requestCategories();
};

	let error;
	function validateName(value) {
		error = null;
		if (value === 'All') {
			error = '"All" has been reserved by the system. Please choose another name.';
		}
		return error;
	}

	return (
		<div>
			<h2>Add A New Category</h2>
			<Formik
			initialValues={{
				type: "categories",
				attributes: {
					name: "",
				}
			}}
			onSubmit={handleSubmit}
			>
			{({ errors, touched }) => (
				<Form>
				<Field type="text" validate={validateName} name="attributes.name" />
				{error && <p>{error}</p>}
				<button type="submit">Create</button>
				</Form>
			)}
			</Formik>
		</div>
	);
}

export default AddCategory;