import React, { useState, useEffect } from "react";
import { navigate } from "@reach/router";
import { Formik, Field, Form } from "formik";
import { Datepicker } from 'react-formik-ui';

function AddTodo() {

	const [categories, setCategories] = useState([]);
	// Retrives UTC offset of the browser
	const utcOffset = new Date().getTimezoneOffset();
	const utcOffsetHours = utcOffset / 60;

	// Adjusts datetime to remove any UTC offset
	function timezonefix(datetime) {
		if (utcOffsetHours <= 0) {
			datetime.setHours(Math.abs(utcOffsetHours));
		} else {
			datetime.setDate(datetime.getDate() - 1);
			datetime.setHours(utcOffsetHours);
		}
		return datetime;
	}

	useEffect(() => {
		const csrfToken = document.querySelector("meta[name=csrf-token]").content;
		const requestCategories = async () => {
			const response = await fetch("/api/categories", {headers: {"X-CSRF-Token": csrfToken}});
			const { data } = await response.json();
			setCategories(data);
		};
		requestCategories();
	}, []);

	const handleSubmit = values => {
		// Fix unwanted utc offset from form.
		if (values.attributes.duedate != "") {
			values.attributes.duedate = timezonefix(values.attributes.duedate);
		}
		const requestTodos = async () => {
		// We get the CSRF token generated by Rails to send it
		// as a header in the request to create a new post.
		// This is needed because with this token, Rails is going to
		// recognize the request as a valid request
		const csrfToken = document.querySelector("meta[name=csrf-token]").content;
		const response = await fetch("/api/todos", {
			method: "POST",
			credentials: "include",
			headers: {
				"Content-Type": "application/vnd.api+json",
				"X-CSRF-Token": csrfToken
			},
			body: JSON.stringify({ data: values })
		});
		if (response.status === 201) {
			navigate("/");
		}
	};
	requestTodos();
};

	return (
		<div>
			<h2>Add A New Todo</h2>
			<Formik
			initialValues={{
				type: "todos",
				attributes: {
					title: "",
					description: "",
					completed: "false",
					duedate: "",
					categoryid: null
				}
			}}
			onSubmit={handleSubmit}
			>
				<Form>
				<label for="attributes.title">Title</label>
				<Field type="text" name="attributes.title" />
				<br />
				<label for="attributes.description">Description</label>
				<Field type="text" name="attributes.description" />
				<br />
				<label for="attributes.duedate">Due Date</label>
				<Datepicker name="attributes.duedate" isClearable />
				<label for="attributes.categoryid">Category</label>
				<Field name="attributes.categoryid" as="select">
					<option value={null}>All</option>
					{categories.map(category => <option value={category.id}>{category.attributes.name}</option>)}
				</Field>
				<br />
				<button type="submit">Create</button>
				</Form>
			</Formik>
		</div>
	);
}

export default AddTodo;