import React from "react";
import DeleteTodo from "./DeleteTodo";

function DeleteCategory(category) {

	const csrfToken = document.querySelector("meta[name=csrf-token]").content;

	const deleteTodos = async () => {
		const response = await fetch("/api/todos?filter[categoryid]="+category.id, {headers: {"X-CSRF-Token": csrfToken}});
		const { data } = await response.json();
		const todos = data;
		todos.map(todo => DeleteTodo(todo.id));
	};
	deleteTodos();

	const deleteCategory = async () => {
		// We get the CSRF token generated by Rails to send it
		// as a header in the request to create a new post.
		// This is needed because with this token, Rails is going to
		// recognize the request as a valid request
		const csrfToken = document.querySelector("meta[name=csrf-token]").content;
		const response = await fetch("/api/categories/" + category.id, {
			method: "DELETE"
		});
		if (response.ok) {
			return true;
		}
	};
	return deleteCategory();
}

export default DeleteCategory;