import React from "react";

function DeleteTodo(todo_id) {
	const requestTodos = async () => {
		// We get the CSRF token generated by Rails to send it
		// as a header in the request to create a new post.
		// This is needed because with this token, Rails is going to
		// recognize the request as a valid request
		const csrfToken = document.querySelector("meta[name=csrf-token]").content;
		const response = await fetch("/api/todos/" + todo_id, {
			method: "DELETE"
		});
		if (response.ok) {
			return true;
		}
	};
	return requestTodos();
}

export default DeleteTodo;