import React from "react";
import { navigate } from "@reach/router";
import { Formik, Field, Form } from "formik";

function EditTodo(props) {

	const todo = props.location.state.todo;

	const handleSubmit = values => {
		const requestTodos = async () => {
		// We get the CSRF token generated by Rails to send it
		// as a header in the request to create a new post.
		// This is needed because with this token, Rails is going to
		// recognize the request as a valid request
		const csrfToken = document.querySelector("meta[name=csrf-token]").content;
		const response = await fetch("/api/todos/" + todo.id, {
			method: "PUT",
			credentials: "include",
			headers: {
				"Content-Type": "application/vnd.api+json",
				"X-CSRF-Token": csrfToken
			},
			body: JSON.stringify({ data: values })
		});
		if (response.ok) {
			navigate("/");
			}
		};
	requestTodos();
	};

	const initialTitle = todo.attributes.title;
	const initialDescription = todo.attributes.description;

	const formikValues = {
		type: "todos",
		id: todo.id,
		attributes: {
			title: initialTitle,
			description: initialDescription,
		}
	}

	return (
		<div>
			<h2>Edit Todo</h2>
			<Formik
			initialValues={formikValues}
			onSubmit={handleSubmit}
			>
				<Form>
				<Field type="text" name="attributes.title" />
				<Field type="text" name="attributes.description" />

				<button type="submit">Update</button>
				</Form>
			</Formik>
		</div>
	);
}

export default EditTodo;