import React from "react";

function MarkTodo(todo_id, status) {
	const requestTodos = async () => {
		// We get the CSRF token generated by Rails to send it
		// as a header in the request to create a new post.
		// This is needed because with this token, Rails is going to
		// recognize the request as a valid request
		const csrfToken = document.querySelector("meta[name=csrf-token]").content;
		const new_status = status ? "false" : "true";
		const values = { type: "todos", id: todo_id, attributes: { completed: new_status } };

		const response = await fetch("/api/todos/" + todo_id, {
			method: "PATCH",
			credentials: "include",
			headers: {
				"Content-Type": "application/vnd.api+json",
				"X-CSRF-Token": csrfToken
			},
			body: JSON.stringify({ data: values })
		});
		if (response.ok) {
			return true;
		}
	};
	return requestTodos();
}

export default MarkTodo;